name: Scan Container Images

on:
  push:
    branches:
      - master

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: CrowdStrike Container Image Scan
        uses: crowdstrike/container-image-scan-action@v1.1.0
        with:
          falcon_client_id: 42e4dbe759554d15bd62bc558389a182
          container_repository: docker.io/library/busybox
        env:
          FALCON_CLIENT_SECRET: ct5A2CvFD3jmXRI817yQ4LdoaBqzVp6fswbH0en9
